---
name: echo_verse
description: Booklet App
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_sizer: ^1.0.5
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.7
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.3
  get: ^4.6.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  fonts:
  - family: GT-Sectra-Fine
    fonts:
    - asset: assets/fonts/GT Sectra Fine Regular.ttf
  assets:
  - assets/
  - assets/fonts/
  - assets/images/
